import React, { ReactNode } from "react";
import Head from 'next/head'
import Navbar from "./Navbar";
import type { NextPage } from 'next'


interface layoutProps{
  children:ReactNode
}

const Layout:NextPage<layoutProps> = ({children}) => {
  return(
  <main
     className="
      overflow-hidden
      bg-zinc-200 text-zinc-800
      flex flex-col items-center justify-center
      min-h-w-screen"
     >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <section 
      className="
        flex flex-col items-center justify-center
        grow min-h-full min-w-full"
       >
    {children} 
      </section>
  </main>
  )
}

export default Layout
